site_name: "PowerDNS-WEB Documentation"
theme:
  name: "material"
  favicon: favicon.ico
  logo: favicon.ico

nav:
  - Main: index.md
  - Install: guide.md
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mark-Shternberg/PowerDNS-WEB
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.medvedev-it.com/MedvedevN/powerdns-web
  generator: false

copyright: '\u00A9 2025 PowerDNS-WEB | Created by <a href="https://medvedev-it.com/" target="_blank">MedvedevN</a> | Made with Material for MkDocs'
