site_name: "PowerDNS-WEB Documentation"
theme:
  name: "material"
  favicon: favicon.ico
  logo: favicon.ico
  
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Install and Upgrade: guide.md
  - Usage:
      - Live Statistics: usage/live-statistics.md
      - Managing DNS Zones: usage/dns-zones.md
      - Managing DNS Records: usage/dns-records.md
      - Forward Zones: usage/forward-zones.md
      - User Management: usage/user-management.md
  - Troubleshooting: troubleshooting.md
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mark-Shternberg/PowerDNS-WEB
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.medvedev-it.com/MedvedevN/powerdns-web
  generator: false

copyright: '© 2025 PowerDNS-WEB | Created by <a href="https://medvedev-it.com/" target="_blank">MedvedevN</a> | Made with Material for MkDocs'
